"""
Pydantic models for Home DIY Repair synthetic data generation.

This module defines the data structure for repair Q&A pairs that will be
generated by the LLM and validated throughout the project phases.

About Pydantic:
Pydantic is a Python library for data validation using type hints. It ensures
data matches a defined structure and automatically validates types, converts
values when possible, and raises clear errors for invalid data. In this project,
Pydantic models enforce that LLM-generated responses contain all required fields
with correct types, guaranteeing consistent, valid synthetic data.
"""

from pydantic import BaseModel, Field
from typing import List


class RepairQA(BaseModel):
    """
    Schema for a home DIY repair Q&A pair.
    
    This model enforces the structure of synthetic repair data, ensuring
    all required fields are present with correct types.
    """
    
    question: str = Field(
        ...,
        description="The repair question from a homeowner",
        min_length=10
    )
    
    answer: str = Field(
        ...,
        description="Detailed answer with practical repair guidance",
        min_length=50
    )
    
    equipment_problem: str = Field(
        ...,
        description="Specific equipment or problem being addressed",
        min_length=5
    )
    
    tools_required: List[str] = Field(
        ...,
        description="List of tools needed for the repair",
        min_items=1
    )
    
    steps: List[str] = Field(
        ...,
        description="Step-by-step repair instructions",
        min_items=2
    )
    
    safety_info: str = Field(
        ...,
        description="Important safety warnings and precautions",
        min_length=20
    )
    
    tips: str = Field(
        ...,
        description="Helpful tips and best practices",
        min_length=20
    )
    
    class Config:
        """Pydantic configuration"""
        json_schema_extra = {
            "example": {
                "question": "How do I fix a leaking faucet?",
                "answer": "To fix a leaking faucet, first turn off the water supply under the sink. Remove the faucet handle by unscrewing the set screw, then remove the packing nut to access the stem. Replace the worn washer or O-ring with a new one of the same size. Reassemble the faucet and turn the water back on to test.",
                "equipment_problem": "Leaking kitchen faucet - worn washer",
                "tools_required": ["adjustable wrench", "screwdriver", "replacement washer"],
                "steps": [
                    "Turn off water supply under sink",
                    "Remove faucet handle",
                    "Remove packing nut",
                    "Replace worn washer",
                    "Reassemble faucet",
                    "Test for leaks"
                ],
                "safety_info": "Always turn off the water supply before starting any plumbing repair. Keep a bucket handy to catch any residual water.",
                "tips": "Take a photo before disassembly to remember how parts fit together. Bring the old washer to the hardware store to ensure you get the correct replacement size."
            }
        }
